<script>
  let count = 0;
  function promisefactory() {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        count++;
        console.log(
          `${count}回目のコールです。時刻：[${new Date().toTimeString()}]`
        );
        if (count === 3) {
          // 3回目のコールでエラー
          reject(count);
        } else {
          resolve(count);
        }
      }, 1000);
    });
  }

  //   thenチェーンで新しいPromiseを生成するために、promisefactory関数を呼び出す必要がある。:
  const instance = promisefactory();
  //   setTimeoutの実行が再度行われるわけではないため、ログが出力されない
  instance
    .then(() => {
      return instance;
    })
    .then(() => {
      return instance;
    })
    .then(() => {
      return instance;
    })
    .catch((errorcount) => {
      console.error(
        `エラーに飛びました。現在のカウントは ${errorcount} です。`
      );
    })
    .finally(() => {
      console.log("処理を終了します。");
    });
  // > 1回目のコールです。時刻：[16:50:00 gmt+0900 (日本標準時)]
  // > 処理を終了します。
</script>
